# Generated by Django 5.1.2 on 2024-10-22 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_department_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='code',
            field=models.CharField(editable=False, max_length=10, unique=True),
        ),
    ]
