# Generated by Django 5.1.2 on 2024-10-29 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_department_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='birth_certificate_photo',
            field=models.ImageField(blank=True, null=True, upload_to='users/birth-certificate-photo'),
        ),
        migrations.AddField(
            model_name='employee',
            name='national_id_photo',
            field=models.ImageField(blank=True, null=True, upload_to='users/national-id-photos', verbose_name=''),
        ),
        migrations.AddField(
            model_name='employee',
            name='passport_photo',
            field=models.ImageField(blank=True, null=True, upload_to='users/passport', verbose_name='Passport'),
        ),
    ]
