# Generated by Django 5.1.2 on 2024-10-22 13:44

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_position_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='salaryMax',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=11),
        ),
        migrations.AddField(
            model_name='position',
            name='salaryMin',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=11),
        ),
    ]
