# Generated by Django 5.1.2 on 2024-10-29 20:40

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_employee_birth_certificate_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(editable=False, max_length=255, unique=True)),
                ('icon_class', models.CharField(max_length=255, verbose_name='Icon Class')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='employee',
            name='birth_certificate_photo',
            field=models.ImageField(blank=True, null=True, upload_to='users/birth-certificate-photo', verbose_name='Birth Certificate'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='national_id_photo',
            field=models.ImageField(blank=True, null=True, upload_to='users/national-id-photos', verbose_name='National ID'),
        ),
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('heading', models.TextField()),
                ('type', models.CharField(choices=[], max_length=50)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='faq/videos/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'avi', 'mkv'])], verbose_name='Video File')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='faq/audio/', validators=[django.core.validators.FileExtensionValidator(['mp3', 'opus'])], verbose_name='Audio File')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.faqcategory')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
