# Generated by Django 5.1.2 on 2024-10-22 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_position_salarymax_position_salarymin'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='sex',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=10, verbose_name='Sex'),
        ),
        migrations.AddField(
            model_name='joboffering',
            name='locations',
            field=models.ManyToManyField(blank=True, to='core.location', verbose_name='Locations'),
        ),
    ]
