# Generated by Django 5.1.2 on 2024-10-22 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_workflow_joboffering_type_alter_position_salarymax_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffering',
            name='due_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='joboffering',
            name='publish_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
