# Generated by Django 5.1.2 on 2024-10-29 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_faqitem_image_file_alter_faqcategory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqitem',
            name='text',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='faqitem',
            name='type',
            field=models.CharField(choices=[('T', 'Text'), ('V', 'Video'), ('I', 'Image'), ('A', 'Audio')], max_length=50),
        ),
    ]
