# Generated by Django 5.1.2 on 2024-10-22 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_joboffering_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='joboffering',
            name='publish_date',
            field=models.DateTimeField(),
        ),
    ]
