# Generated by Django 5.1.2 on 2024-10-22 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_location_active_alter_joboffering_publish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='keywords',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
