# Generated by Django 5.1.2 on 2024-10-29 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_faqitem_text_alter_faqitem_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqcategory',
            name='description',
            field=models.CharField(default='Donec sagittis urna eu leo', max_length=255),
        ),
        migrations.AlterField(
            model_name='faqitem',
            name='image_file',
            field=models.FileField(blank=True, null=True, upload_to='faq/images/', verbose_name='Image File'),
        ),
    ]
