# Generated by Django 5.1.2 on 2024-10-23 08:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_task_task_type_jobapplication_jobassignments'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOfferingRequiredDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('optional', models.BooleanField(default=False)),
                ('job_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_documents', to='core.joboffering', verbose_name='Job Offering')),
            ],
            options={
                'verbose_name': 'Job Offering Required Document',
                'verbose_name_plural': 'Job Offering Required Documents',
            },
        ),
    ]
