# Generated by Django 5.1.2 on 2024-10-23 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_jobofferingrequireddocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='active_assignment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_employee', to='core.jobassignments'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='nationalIdNo',
            field=models.CharField(blank=True, help_text='format:XX-XXXXXX-A-XX', max_length=150, null=True, verbose_name='Nation ID Number'),
        ),
        migrations.AlterField(
            model_name='jobassignments',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Employee'),
        ),
    ]
