# Generated by Django 5.1.2 on 2024-10-23 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_employee_active_assignment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobassignments',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobassignments',
            name='location',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.location', verbose_name='Location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobassignments',
            name='status',
            field=models.CharField(choices=[('open', 'Active'), ('closed', 'Terminated'), ('inactive', 'Suspended')], default='open', max_length=10),
        ),
        migrations.AddField(
            model_name='jobassignments',
            name='termination_description',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobassignments',
            name='termination_reason',
            field=models.CharField(choices=[('NEW POSITION', 'New Position'), ('DISCIPLINARY', 'Disciplinary')], default='NEW POSITION', max_length=50),
        ),
        migrations.AddField(
            model_name='jobassignments',
            name='type',
            field=models.CharField(choices=[('FULL TIME', 'Full Time'), ('PART TIME', 'Part Time'), ('CONTRACT', 'Contract')], default='FULL TIME', max_length=10),
        ),
        migrations.AddField(
            model_name='joboffering',
            name='contract_months',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
