# Generated by Django 5.1.2 on 2024-10-23 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_department_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobassignments',
            name='job_offering',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.joboffering', verbose_name='Job Offering'),
        ),
    ]
