# Generated by Django 5.1.2 on 2024-10-23 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_jobassignments_job_offering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobassignments',
            name='job_offering',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_employees', to='core.joboffering', verbose_name='Job Offering'),
        ),
    ]
