# Generated by Django 5.1.2 on 2024-10-23 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_jobassignments_job_offering'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobapplication',
            options={'verbose_name': 'Job Application', 'verbose_name_plural': 'Job Applications'},
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='job_offering',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.joboffering', verbose_name='Job Offering'),
        ),
        migrations.AlterField(
            model_name='joboffering',
            name='locations',
            field=models.ManyToManyField(to='core.location', verbose_name='Locations'),
        ),
    ]
