# Generated by Django 5.1.2 on 2024-10-23 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_jobapplication_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffering',
            name='publish_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
