# Generated by Django 5.1.2 on 2024-10-23 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_joboffering_publish_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['parent__name', 'name'], 'verbose_name': 'Department', 'verbose_name_plural': 'Departments'},
        ),
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('parent', 'name')},
        ),
    ]
