# Generated by Django 5.1.2 on 2024-10-23 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_department_options_alter_department_code_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('parent', 'code'), ('parent', 'name')},
        ),
    ]
