# Generated by Django 5.1.2 on 2024-10-23 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_department_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_number',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
