# Generated by Django 5.1.2 on 2024-10-23 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_employee_employee_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_number',
            field=models.CharField(editable=False, max_length=10, unique=True),
        ),
    ]
