# Generated by Django 5.1.2 on 2024-10-23 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_employee_employee_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'verbose_name': 'Assignment', 'verbose_name_plural': 'Assignments'},
        ),
        migrations.AlterUniqueTogether(
            name='assignment',
            unique_together={('task', 'assigned_to')},
        ),
        migrations.RemoveField(
            model_name='task',
            name='jobOffering',
        ),
        migrations.AddField(
            model_name='joboffering',
            name='workflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_offerings', to='core.workflow'),
        ),
        migrations.AddField(
            model_name='task',
            name='stage',
            field=models.CharField(choices=[('pre-onboarding', 'Pre-Onboarding'), ('onboarding', 'Onboarding')], default='pre-onboarding', max_length=14),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Done', 'Done')], default='Pending', max_length=14),
        ),
        migrations.AlterField(
            model_name='task',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.workflow'),
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='employee_name',
        ),
    ]
