# Generated by Django 5.1.2 on 2024-10-23 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_task_document_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='address_line_1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Address Line 1'),
        ),
        migrations.AddField(
            model_name='employee',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Address Line 2'),
        ),
    ]
