# Generated by Django 5.1.2 on 2024-10-23 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_employee_address_line_1_employee_address_line_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffering',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_offerings', to='core.workflow'),
        ),
    ]
