# Generated by Django 5.1.2 on 2024-10-23 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_joboffering_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobassignments',
            name='workflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_assignments', to='core.workflow'),
        ),
    ]
