# Generated by Django 5.1.2 on 2024-10-23 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_jobassignments_workflow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobassignments',
            name='workflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_assignments', to='core.workflow', verbose_name='Workflow Template'),
        ),
    ]
