# Generated by Django 5.1.2 on 2024-10-23 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_jobassignments_workflow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobassignments',
            name='due_date',
        ),
        migrations.AddField(
            model_name='task',
            name='days',
            field=models.PositiveIntegerField(default=0, verbose_name='Days from Start Date'),
        ),
        migrations.AlterField(
            model_name='jobassignments',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_assignments', to='core.workflow', verbose_name='Onboarding Workflow'),
        ),
    ]
