# Generated by Django 5.1.2 on 2024-10-24 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_assignment_createdat_assignment_updatedat_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobassignments',
            options={'verbose_name': 'Job Assignment', 'verbose_name_plural': 'Job Assignments'},
        ),
        migrations.AlterField(
            model_name='jobassignments',
            name='termination_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
