# Generated by Django 5.1.2 on 2024-10-25 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_alter_jobassignments_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Not Done'), ('Submitted', 'Pending'), ('Done', 'Done')], default='Pending', max_length=14),
        ),
        migrations.AlterField(
            model_name='task',
            name='document_name',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='tasks/documents', verbose_name='Instruction Document'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('file', 'File Upload'), ('meeting', 'Meeting'), ('interview', 'Interview'), ('training', 'Training Session')], max_length=10),
        ),
    ]
