# Generated by Django 5.1.2 on 2024-10-25 14:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_alter_assignment_status_alter_task_document_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('level', models.CharField(choices=[('success', 'Success'), ('info', 'Information'), ('warning', 'Warning'), ('error', 'Error')], default='success', max_length=20, verbose_name='Level')),
                ('subject', models.CharField(default='Subject', max_length=255, verbose_name='Subject')),
                ('description', models.TextField(default='Description', verbose_name='Description')),
                ('unread', models.BooleanField(db_index=True, default=True, verbose_name='Unread')),
                ('public', models.BooleanField(db_index=True, default=True, verbose_name='public')),
                ('deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('emailed', models.BooleanField(db_index=True, default=False, verbose_name='emailed')),
                ('data', models.JSONField(blank=True, null=True, verbose_name='data')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Recipient')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ('-createdAt',),
                'unique_together': {('recipient', 'unread')},
            },
        ),
    ]
