# Generated by Django 5.1.2 on 2024-10-25 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='task',
        ),
        migrations.AddField(
            model_name='document',
            name='assignment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.assignment'),
            preserve_default=False,
        ),
    ]
