# Generated by Django 5.1.2 on 2024-10-25 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_document_createdat_document_updatedat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='assignment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.assignment'),
        ),
    ]
