# Generated by Django 5.1.2 on 2024-10-25 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_alter_document_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='File'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='File Name'),
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
