# Generated by Django 5.1.2 on 2024-10-25 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_assignment_file_assignment_file_name_delete_document'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notification',
            unique_together=set(),
        ),
    ]
