# Generated by Django 5.1.2 on 2024-10-25 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_alter_notification_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='hours',
            field=models.PositiveIntegerField(default=0, verbose_name='Hours from Start Date'),
        ),
    ]
