# Generated by Django 5.1.2 on 2024-10-25 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_task_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='minutes',
            field=models.PositiveIntegerField(default=0, verbose_name='Hours from Start Date'),
        ),
    ]
