# Generated by Django 5.1.2 on 2024-10-26 06:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_task_minutes'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyField',
            fields=[
                ('ordinal', models.IntegerField(auto_created=True, default=1)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(editable=False, max_length=255, unique=True)),
                ('type', models.CharField(choices=[('D', 'Date'), ('B', 'Boolean'), ('E', 'Date Time'), ('T', 'Short Text'), ('L', 'Long Text'), ('N', 'Number'), ('S', 'Select Choice'), ('R', 'Radio Choice')], max_length=50)),
                ('cssClass', models.CharField(blank=True, default='col-span-1', max_length=255, null=True, verbose_name='Css Classes')),
                ('label', models.CharField(max_length=255)),
                ('helpText', models.CharField(blank=True, max_length=255, null=True)),
                ('placeholder', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.BooleanField(default=False)),
                ('required', models.BooleanField(default=False)),
                ('allowCustom', models.BooleanField(default=False)),
                ('dp', models.PositiveIntegerField(default=0)),
                ('minimum', models.DecimalField(decimal_places=3, default=0, max_digits=11)),
                ('maximum', models.DecimalField(decimal_places=3, default=0, max_digits=11)),
            ],
            options={
                'verbose_name': 'Survey Field',
                'verbose_name_plural': 'Survey Fields',
                'ordering': ['ordinal'],
            },
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ('-unread', '-createdAt'), 'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.AlterField(
            model_name='notification',
            name='level',
            field=models.CharField(choices=[('success', 'Success'), ('info', 'info'), ('warning', 'Warning'), ('error', 'Danger')], default='success', max_length=20, verbose_name='Level'),
        ),
        migrations.CreateModel(
            name='SurveyRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SurveyFieldChoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='core.surveyfield')),
            ],
            options={
                'verbose_name': 'Survey Field Choice',
                'verbose_name_plural': 'Survey Field Choices',
                'ordering': ['field', 'name'],
                'unique_together': {('field', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SurveyRecordValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('textValue', models.TextField(blank=True, null=True)),
                ('numberValue', models.DecimalField(blank=True, decimal_places=3, max_digits=11, null=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='core.surveyfield')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='core.surveyrecord')),
            ],
            options={
                'unique_together': {('record', 'field')},
            },
        ),
    ]
