# Generated by Django 5.1.2 on 2024-10-26 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_surveyfield_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyfield',
            name='ordinal',
            field=models.IntegerField(default=1),
        ),
    ]
