# Generated by Django 5.1.2 on 2024-10-26 07:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_alter_surveyfield_ordinal'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyHeading',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='surveyfield',
            name='cssClass',
            field=models.CharField(blank=True, default='col-12 col-sm-6', max_length=255, null=True, verbose_name='Css Classes'),
        ),
        migrations.AddField(
            model_name='surveyfield',
            name='heading',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='survey_fields', to='core.surveyheading'),
            preserve_default=False,
        ),
    ]
