# Generated by Django 5.1.2 on 2024-10-26 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_alter_surveyheading_options_surveyheading_ordinal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyfield',
            name='ordinal',
            field=models.IntegerField(default=1, unique=True),
        ),
        migrations.AlterField(
            model_name='surveyheading',
            name='ordinal',
            field=models.IntegerField(default=1, unique=True),
        ),
    ]
